---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: exampleSite/content/english/gallery
  label: Gallery (en)
  create: documents
  match: "**/*"
  templates:
  - post
- type: directory
  path: exampleSite/content/german/gallery
  label: Gallery (de)
  create: documents
  match: "**/*"
  templates:
  - post
- type: directory
  path: exampleSite/content/english/sightseeing
  label: Sightseeing (en)
  create: documents
  match: "**/*"
  templates:
  - project
- type: directory
  path: exampleSite/content/german/sightseeing
  label: Sightseeing (de)
  create: documents
  match: "**/*"
  templates:
  - project
- type: directory
  path: exampleSite/content/english/our_story
  label: Our story (en)
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/german/our_story
  label: Our Story (de)
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/english/service
  label: Service (en)
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/french/service
  label: Service (fr)
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/english/hotels
  label: Hotels (en)
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/german/hotels
  label: Hotels (de)
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/english/faq
  label: FAQ (en)
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/german/faq
  label: FAQ (de)
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/english/contact
  label: Contact (en)
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/french/contact
  label: Contact (fr)
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/english/pages
  label: Created Pages (en)
  create: documents
  match: "**/*"
  templates:
  - new-page
- type: directory
  path: exampleSite/content/german/pages
  label: Created Pages (de)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: directory
  path: exampleSite/content/english
  label: All Pages (en)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: directory
  path: exampleSite/content/german
  label: All Pages (de)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: directory
  path: exampleSite/data/en
  label: Data (en)
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/data/de
  label: Data (de)
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/i18n
  label: i18n
  create: documents
  match: "**/*"
- type: heading
  label: Configuration
- type: directory
  path: exampleSite
  label: Configuration
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
