################################# Default configuration ###################
baseURL = "http://examplesite.org"
title = "Airspace | Creative Agency Hugo Template"
theme = "airspace-hugo"
themesDir = "../.."
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

################################# Outputs #################################
# hugo outputs
[outputs]
home = ["HTML"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/slick/slick.css"
attributes = ""

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
attributes = "defer"


############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_width = "150px"
# Meta data
description = "This is meta description"
author = "Themefisher"
# Contact Information
mobile = "0124857985320"
email = "demo@email.com"
location = "North Main Street,Brooklyn Australia"
# Contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "rsvp"

# google map
[params.gmap]
enable = true
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

############################# social site ########################
[[params.social]]
icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-pinterest-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-dribbble-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"


######################### english navigation #############################
# main menu
[[Languages.en.menu.main]]
name = "Home"
URL = "/"
weight = 1

[[Languages.en.menu.main]]
name = "Our Story"
URL = "our_story"
weight = 2

[[Languages.en.menu.main]]
name = "Gallery"
URL = "gallery"
weight = 3

[[Languages.en.menu.main]]
name = "Hotels"
URL = "hotels"
weight = 4

[[Languages.en.menu.main]]
name = "Sightseeing"
URL = "sightseeing"
weight = 5

[[Languages.en.menu.main]]
name = "RSVP"
URL = "rsvp"
weight = 6

[[Languages.en.menu.main]]
name = "FAQ"
URL = "faq"
weight = 7

# footer menu
[[Languages.en.menu.footer]]
name = "Our Story"
URL = "our_story"
weight = 1

[[Languages.en.menu.footer]]
name = "Gallery"
URL = "gallery"
weight = 2

[[Languages.en.menu.footer]]
name = "Hotels"
URL = "hotels"
weight = 3

[[Languages.en.menu.footer]]
name = "Sightseeing"
URL = "sightseeing"
weight = 4

[[Languages.en.menu.footer]]
name = "RSVP"
URL = "rsvp"
weight = 5

[[Languages.en.menu.footer]]
name = "FAQ"
URL = "faq"
weight = 6

################################ German Language ########################
[Languages.de]
languageName = "De"
languageCode = "de-de"
contentDir = "content/german"
weight = 2
# copyright
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"


######################### german navigation #############################
# main menu
[[Languages.de.menu.main]]
name = "Home"
URL = "/"
weight = 1

[[Languages.de.menu.main]]
name = "Unsere Geschichte"
URL = "our_story"
weight = 2

[[Languages.de.menu.main]]
name = "gallerie"
URL = "gallery"
weight = 3

[[Languages.de.menu.main]]
name = "Hotels"
URL = "hotels"
weight = 4

[[Languages.de.menu.main]]
name = "Sightseeing"
URL = "sightseeing"
weight = 5
  
[[Languages.de.menu.main]]
name = "RSVP"
URL = "rsvp"
weight = 6

[[Languages.de.menu.main]]
name = "FAQ"
URL = "faq"
weight = 7


# footer menu
[[Languages.de.menu.footer]]
name = "Unsere Geschichte"
URL = "our_story"
weight = 1

[[Languages.de.menu.footer]]
name = "Gallerie"
URL = "gallery"
weight = 2

[[Languages.de.menu.footer]]
name = "Hotels"
URL = "hotels"
weight = 3

[[Languages.de.menu.footer]]
name = "Sightseeing"
URL = "sightseeing"
weight = 4

[[Languages.de.menu.footer]]
name = "RSVP"
URL = "rsvp"
weight = 5

[[Languages.de.menu.footer]]
name = "FAQ"
URL = "faq"
weight = 6